Revert "Migrate LayoutImportExportHelper to use the ModelWriter ..."
Revert submission 38922045-migrate-layout-export

Reason for revert: Build possibly broke becuse of the added dependency
Error: https://android-build.googleplex.com/builds/submitted/15041136/test_suites_arm64-trunk_staging/latest/logs/build_error.log?referrer=crowsnest

Reverted changes: /q/submissionid:38922045-migrate-layout-export

Change-Id: If9e79876597ed657cfa2266a2cbdb686e2c4a726